const projects = [
  {
    id: "shubh-city",
    name: "Shubh City",
    location: "Main Delhi Road, Jaipur",
    description:
      "Shubh City offers well-planned, spacious homes in Jaipur with modern comforts, premium amenities, and a vibrant community where living meets elevated family lifestyle.",
    amenities: [
      "Swimming Pool",
      "Reading room",
      "Kids Play Area",
      // "Indoor Games room",
      "Yoga Deck",
      "Gym",
      // "Banquet hall",
      // "Guest Room",
      // "Laundary",
    ],
    image: "/images/shubh-city/Shubh City Apartments.jpg",
  },
  {
    id: "palm-studio",
    name: "Palm Studio",
    location: "Main Delhi Road, Jaipur",
    description:
      "Palm Studio by Shubham Group brings modern studio apartments in Jaipur with smart design, stylish comfort, and amenities like a gym, pool, and mini theater crafted for today’s lifestyle.",
    amenities: [
      "Gymnasium",
      "Yoga Room",
      "Library",
      "Indoor Games",
      // "Cafeteria",
      "Laundry",
    ],
    image: "/images/palm-studio/plam-studio1.jpg",
  },
  {
    id: "aditya-villa",
    name: "Aditya Villa",
    location: "Tonk Road, Jaipur",
    description:
      "Aditya Villa offers stylish villas in Jaipur, combining modern design with comfort. Enjoy serene surroundings and premium amenities for a truly elevated living experience.",
    amenities: [
      "Open Gym",
      "Kids play area",
      // "Jogging track",
      "Yoga park",
      "Meditation area",
      // "Senior citizen area",
      // "Sitting bench",
      // "Community hall",
      "Temple",
      "Commercial shops",
    ],
    image: "/images/aditya-villa/ADITYA VILLA  VIEW09.jpg",
  },
  {
    id: "shubh-villa",
    name: "Shubh Villa",
    location: "Ajmer Road, Jaipur",
    description:
      "Shubh Villa offers elegant, spacious villas in Jaipur with modern layouts, premium amenities, and a lifestyle of comfort and luxury.",
    amenities: [
      "Swimming Pool",
      "Skating Ring",
      "Yoga Deck",
      // "Kid's Play Area",
      "Club Area",
      // "Library",
      // "Indoor Games Area",
      "Badminton Court",
      // "Senior Citizen's Communal Area",
      // "Designer Walk-Ways",
      // "Yoga Corner",
    ],
    image: "/images/shubh-villa/2.jpg",
  },
  {
    id: "shubh-nikunj",
    name: "Shubh Nikunj",
    location: "Mohanpur, Jaipur",
    description:
      "Shubh Nikunj offers ready-to-move 2 & 3 BHK apartments in Jaipur, combining smart design, modern comforts, and amenities like a pool, gym, and mini theater for a refined lifestyle.",
    amenities: [
      "Swimming Pool",
      "Gym",
      "Jogging Track",
      // "Kids Play Area",
      // "Indoor Games",
      "Mini Theatre",
      // "Guest Rooms",
      // "Community Hall",
      // "Library",
      // "Yoga Deck",
      "Rooftop Garden",
      // "Senior Citizen Area",
      // "🛡️ CCTV Security",
    ],
    image: "/images/shubh-nikunj/nikunj/Aerial 1-new.jpg",
  },
];

export { projects };
